CREATE TABLE `albums` (
  `id` integer NOT NULL PRIMARY KEY AUTOINCREMENT
,  `ALBUM_ID` varchar(45) NOT NULL
,  `ARTIST_ID` varchar(45) NOT NULL
, IS_CRAWL integer NOT NULL DEFAULT '0',  UNIQUE (`ALBUM_ID`,`ARTIST_ID`)
);
CREATE TABLE `artists` (
  `id` integer NOT NULL DEFAULT '0'
,  `ARTIST_ID` varchar(45) NOT NULL
,  `ARTIST_NAME` text NOT NULL
,  `IS_CRAWL` integer NOT NULL DEFAULT '0'
,  UNIQUE (`ARTIST_ID`)
);
CREATE TABLE `comments` (
  `id` integer NOT NULL PRIMARY KEY AUTOINCREMENT
,  `MUSIC_ID` varchar(45) NOT NULL
,  `COMMENTS` varchar(45) DEFAULT NULL
,  `DETAILS` varchar(45) DEFAULT NULL
,  UNIQUE (`MUSIC_ID`,`COMMENTS`)
);
CREATE TABLE `musics` (
  `id` integer NOT NULL PRIMARY KEY AUTOINCREMENT
,  `MUSIC_ID` varchar(45) NOT NULL
,  `MUSIC_NAME` varchar(45) DEFAULT NULL
,  `ALBUM_ID` varchar(45) DEFAULT NULL
, IS_CRAWL integer NOT NULL DEFAULT '0',  UNIQUE (`MUSIC_ID`,`ALBUM_ID`)
);
